### ISSUE TITLE
Chapter 2.5.1

### ISSUE THREAD

**Issue by calmeidavieira** [t-kalinowski/deep-learning-with-R-2nd-edition-code#2]
Hello,

Could you please check if you get same output for the following chunk of code (section 2.5.1)?

```
model <- naive_model_sequential(list(
   layer_naive_dense(input_size = 28 * 28, output_size = 512,
                     activation = tf$nn$relu),
   layer_naive_dense(input_size = 512, output_size = 10,
                     activation = tf$nn$softmax)
 ))
```
Error in random_array(w_shape, min = 0, max = 0.1) : 
  could not find function "random_array"

Some additional information:
R version 4.2.1 (2022-06-23 ucrt)
Loaded Tensorflow version 2.9.1

Apologies if that was answered somewhere else and/of I missed to include add information.

Regards. Cicero

**Comment by t-kalinowski** [comment]
Welcome! :) 

The `random_array` function is defined earlier in the chapter: 
https://github.com/t-kalinowski/deep-learning-with-R-2nd-edition-code/blob/9f8b6d08dbb8d6565e4f5396e509aaea3e242b84/ch02.R#L177-L179
