### ISSUE TITLE
Plot(model) does not see graphviz in R on Windows

### ISSUE THREAD

**Issue by ggeeoorrgg** [t-kalinowski/deep-learning-with-R-2nd-edition-code#4]
Hi! 
I am triyng to reproduce in R some examples from Chapter 7. (Win 10x64,  22H2)
Calling plot(model) after Listing 7.11 falls with error: "See ?keras::plot.keras.engine.training.Model for instructions on how to install graphviz and pydot Error in plot(model) : ImportError: You must install pydot (pip install pydot) and install graphviz (see instructions at https://graphviz.gitlab.io/download/) for plot_model to work."
But I have installed both pydot and graphviz - I did it a lot of times in different ways. Currently it looks like this:

`reticulate::py_list_packages(envname = "r-reticulate", type = "conda" )`
 ...................
graphviz          7.1.0         graphviz=7.1.0 conda-forge
 ...................
pydot              1.4.2        pydot=1.4.2 conda-forge

`> reticulate::py_config()`
python:         C:/Users/UserName/miniconda3/envs/r-reticulate/python.exe
libpython:      C:/Users/UserName/miniconda3/envs/r-reticulate/python38.dll
pythonhome:     C:/Users/UserName/miniconda3/envs/r-reticulate
version:        3.8.16 | packaged by conda-forge | (default, Feb  1 2023, 15:53:35) [MSC v.1929 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Users/UserName/miniconda3/envs/r-reticulate/Lib/site-packages/numpy
numpy_version:  1.24.2

After many hours of searching on the internet I still can't manage to fix this error. So I would appreciate you
help me to solve it.

**Comment by t-kalinowski** [comment]
Hi, thanks for reporting. 
I responded to the issue here https://github.com/rstudio/keras/issues/1337, which is I think the same issue.

As a workaround until this is fixed, you can run your `plot()` calls outside the RStudio IDE (not ideal, I know).
